sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgflags-dev
  - curl -o benchmark-1.0.0.zip -L https://github.com/google/benchmark/archive/v1.0.0.zip
  - unzip benchmark-1.0.0.zip

install:
  - pushd benchmark-1.0.0
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Release . && make
  - sudo make install
  - popd
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make

script:
  - ./geometry/s2test --benchmark_filter=XXX
